//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int std_id { get; set; }
        public string cou { get; set; }
    
        public virtual info info { get; set; }
    }
}
