//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<book> books { get; set; }
        public DbSet<course> courses { get; set; }
        public DbSet<info> infoes { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Mark> Marks { get; set; }
        public DbSet<paying> payings { get; set; }
        public DbSet<Tinfo> Tinfoes { get; set; }
        public DbSet<Tpayment> Tpayments { get; set; }
    }
}
